=head1 NAME 

uSAC::FastPack - Asynchronous local and Remote applciation Broker

=head1 SYNOPSIS

  use uSAC::FastPack::Broker;

=head1 DESCRIPTION

Povides the a brokerage mechanism for broadcasting and listening (subscribing)
to named messages (topics). The transport encoding is C<Data::FastPack> which
gives flexibiliby and efficiency

=head1 USAGE

=head2 API

=head3 Default Broker


  $uSAC::Main::Default_Broker;

A broker is already created as a part of the C<uSAC::Main> namespace which is
present for all uSAC applciations.


=head3 Creating a Broker

  my $node= uSAC::FastPack::Broker->new;


A broker is a node in a potentiall larger system. 

